obj-y += board.o
lwl-y += lowlevel.o
bbenv-y += defaultenv-physom-imx6
bbenv-y += defaultenv-physom-imx6-phycore
bbenv-y += defaultenv-physom-imx6ul-phycore
bbenv-y += defaultenv-physom-imx6ull-grisp2
